error: remove usage of github.com/hashicorp/go-multierror
The internal replacement is a simpler implementation which only supports enough
functionality for the places where github.com/hashicorp/go-multierror was used
before.

The implementation is taken from
https://github.com/container-orchestrated-devices/container-device-interface
commit ec52f5a1354dcc2b25dd096ebef5b81e26db08c3

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>