WIP: add vm-cxl-{hw,hotplug,hotremove}
Either of the CXL memory devices in the same CXL switch can be
hotplugged. Once hotplugged one is hotremoved, the other can be
hotplugged, and it works, too.

However, if devices are plugged at the same time, the latter will not
be accessible. dmesg shows:
[  114.941250] cxl_port port2: unable to add dport0-0000:0e:00.0 non-unique port id (0000:0e:01.0)
[  114.942037] cxl_mem mem1: probe with driver cxl_mem failed with error -16

And once a hotplugged device is hotremoved, Qemu needs to be restarted
before it can be hotplugged again, otherwise Qemu will complain:
(qemu) device_add cxl-type3,bus=cxlsw_uscxlrp0_0_ds1,volatile-memdev=beram_cxl_memdev1__bus_cxlsw_uscxlrp0_0_ds1__sn_0xC813DB27,id=cxl_memdev1,sn=0xC813DB27
Error: Duplicate device ID 'cxl_memdev1'

As if the same device_id could not be used after "device_del <device-id>".